before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 6
  - 7
  ignore:
  - goos: darwin
    goarch: 386
archives:
- format: gz
  replacements:
    amd64: x86_64
    386: i386
    darwin: macos
  format_overrides:
  - goos: windows
    format: zip
  - goos: darwin
    format: zip
  files:
  - none*
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
